#!/bin/sh

THIS_SCRIPT_LOC="$(pwd)"
COMMON_PATHS="${THIS_SCRIPT_LOC}/common_paths"

errnexit() { echo "${1}"; >&2; exit 1 }

unlink_files() {
    INPUT_FILE="${1}"
    TARGET_BASEDIR="${2}"
    
    while IFS= read -r line_path; do
        local ACTION="[Delinking]"
        local TARGET_LINK="${TARGET_BASEDIR}/${line_path}"
        echo "${ACTION} -/> ${TARGET_LINK}"
        #rm -rf "${TARGET_LINK}" \
        #|| errnexit "Failed to remove symlink ${TARGET_LINK}"
    done < "${INPUT_FILE}"
}

unlink_os_specific() {
    local OS="${1}"
    case "${OS}" in
        "openbsd")
            echo "Setting up configs for ${OS}"
            OS_CONFIG_DIR="${THIS_SCRIPT_LOC}/${OS}"
            unlink_files "${OS_CONFIG_DIR}/link_paths" "${HOME}"
            ;;
        *)
            ;;
    esac
}

run() {
    unlink_files "${COMMON_PATHS}" "${HOME}"
}
