#!/bin/sh

power_info() {
    local battery_time_remaining=$(acpiconf -i 0 | grep time | cut -d ':' -f 2-3 | tr -d '[:space:]')
    local battery_capacity=$(acpiconf -i 0 | grep 'Remaining capacity' | cut -d ':' -f 2 | tr -d '[:space:]' | tr -d '%')
    local battery_status=$(acpiconf -i 0 | grep 'State' | cut -d ':' -f 2 | tr -d '[:space:]')

    if [ "$battery_status" = "charging" ]; then
        local battery_icon=
    else
        if [ "$battery_capacity" -ge 90 ]; then
            local battery_icon=
        elif [ "$battery_capacity" -ge 60 ]; then
            local battery_icon=
        elif [ "$battery_capacity" -ge 35 ]; then
            local battery_icon=
        elif [ "$battery_capacity" -ge 7 ]; then
            local battery_icon=
        else
            local battery_icon=
        fi
    fi

    if [ "$battery_time_remaining" = "unknown" ]; then
        local battery_time_remaining="unknown"
    fi

    local hourglass_icon=""

    power_status="$battery_icon $battery_capacity% | $hourglass_icon ($battery_time_remaining)"

}

cpu_temp() {
    local cpu_temperature=$(sysctl -a | grep temperature | head -1 | cut -wf 2)
    cpu_temp_status="CPU: $cpu_temperature"
}

ram() {
    local ram_icon=
    local free_mem=$(vmstat -h | sed -n 3p | cut -wf 5)
    mem_status="$ram_icon $free_mem"
}

time_clock() {
    local clock_icon=
    local time=$(date +"%I:%M%p")
    time_status="$clock_icon $time"
}

cmus_music() {

    local cmus_info="$(cmus-remote -Q 2>/dev/null)"
    local playing_status="$(echo "$cmus_info" | grep status)"

    case "$playing_status" in
        *paused*) 
            local music_icon=
            local song=$(echo "$cmus_info" | grep file | rev | cut -d "/" -f 1 | rev | cut -d "." -f 1)
            ;;
        *playing*)
            local music_icon=
            local song=$(echo "$cmus_info" | grep file | rev | cut -d "/" -f 1 | rev | cut -d "." -f 1)
            ;;
        *)
            local music_icon=
            local song="Not playing"
            ;;
    esac
    cmus_status="$music_icon $song"
}

wifi() {
    local ssid=$(ifconfig wlan0 | grep ssid | cut -wf 3 | cut -c 1-7)
    local status=$(ifconfig wlan0 | grep flags | grep UP)

    if [ ! -z $ssid ]; then
        local wifi_icon=

        if [ $(echo $ssid | wc -c) -ge 7 ]; then
            local ellipsis="..."
        else
            local ellipsis=""
        fi
    else
        local wifi_icon=
        local ssid="Searching..."
    fi
    
    if [ "$status" = "" ]; then
        local status_icon=
        local ssid="No Wifi"
        local wifi_icon=
    else
        local status_icon=
    fi


    wifi_status="$wifi_icon $ssid$ellipsis"
    wifi_device_status="$status_icon"
    
}

gen_statusbar() {
    wifi
    cmus_music
    power_info
    cpu_temp
    ram
    time_clock

    statusbar="$cmus_status | $mem_status | $cpu_temp_status | $power_status | $time_status | $wifi_status | $wifi_device_status"
}

while true; do
    gen_statusbar
    xsetroot -name " $statusbar "
    sleep 5
done
