#!/bin/sh

EXT_MONITOR_POS=$1


if [ $EXT_MONITOR_POS = "r" ]; then
    xrandr --output eDP1 --auto --output DP1 --auto --scale '1.5x1.5' --right-of eDP1
else
    xrandr --output eDP1 --auto --output DP1 --auto --scale '1.5x1.5' --left-of eDP1
fi

~/.fehbg
